### ISSUE TITLE
pip install as mentioned in doc is not working

### ISSUE THREAD

**Issue by vinu76jsr** [kitconcept/robotframework-djangolibrary#1]
In docs it is mentioned, to install this library

```
 pip install robotframework-djangolibrary
```

which seems to not be working, output is

``````
Downloading/unpacking robotframework-djangolibrary
  Could not find any downloads that satisfy the requirement robotframework-djangolibrary
Cleaning up...
No distributions at all found for robotframework-djangolibrary
Storing debug log for failure in /Users/******/.pip/pip.log```
``````

**Comment by tisto** [comment]
@vinu76jsr There is no release yet. Will try to find time to make one...I wasn't aware that anyone is actually using this. :)

**Comment by tisto** [comment]
Here is a first alpha release: https://pypi.python.org/pypi/robotframework-djangolibrary
