### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by petersohn** [kitconcept/robotframework-djangolibrary#16]
What is this `requests` library that is needed here? The only module I can find with this name is `django.contrib.sites.requests`, but if I try to explicitly import that, the tests trying to use it fail. What requirement do I need to install for this to work? Please also mention such dependencies in the readme.

**Comment by tisto** [comment]
@petersohn sorry, I must have missed your bug report. The Python 'requests' library is declared as a dependency in setup.py. Therefore all you need to do is:

pip install robotframework-djangolibrary

This will automatically fetch the requests library. If this is not the case please provide an error trace and a more detailed description of how to reproduce the problem.

**Comment by tisto** [comment]
@petersohn will close the issue now. Feel free to re-open if you have additional information.
