### ISSUE TITLE
Remove django from requirements.txt

### ISSUE THREAD

**Issue by andybak** [kitconcept/robotframework-djangolibrary#2]
So this doesn't happen:

```
> pip install robotframework-djangolibrary
Installing collected packages: Django
  Found existing installation: Django 1.6.11
    Uninstalling Django-1.6.11:
      Successfully uninstalled Django-1.6.11
Successfully installed Django-1.8.2
```

Considering I'm writing tests for a Django 1.6 project to facilitate upgrading django to 1.8 - I certainly wasn't expecting my test framework to jump the gun before I'd even written any tests!

**Comment by tisto** [comment]
@andybak thanks for reporting. Will look into it.
