### ISSUE TITLE
Add gitflow or improve the docs on methodology to help development

### ISSUE THREAD

**Issue by cdvv7788** [kitconcept/robotframework-djangolibrary#21]
I created a pull request for something minor, probably something that does not deserve a release or something, however i sent it against the master branch on this repository.
The branch name does not give a clue about what is the development one, so it can be kinda confusing when someone wants to help. Clarifying this could be a good idea.

**Comment by tisto** [comment]
It is a common convention that the master branch is the main development branch. This is essentially what CI is about. gitflow does not make any sense with travis in my opinion...
