### ISSUE TITLE
Use a test database

### ISSUE THREAD

**Issue by cdvv7788** [kitconcept/robotframework-djangolibrary#24]
Django tests create a test database before proceeding. Currently djangolibrary doesn't, and it clears the database after finishing tests.
I think that it would be a good idea to be able to work on separate databases to avoid breaking things/wiping data unexpectedly.

**Comment by tisto** [comment]
That would be a nice enhancement indeed.

**Comment by ghost** [comment]
I may have a bit of time to look into this. @tisto Do you have any advice regarding how we could approach this?

**Comment by tisto** [comment]
@amarandon there is pytest-dbfixture:

https://pypi.python.org/pypi/pytest-dbfixtures

I guess we do not want to rely on pytest, since it is unfortunately not the default testing framework in Django. Though, something along those lines would be nice to have...
