### ISSUE TITLE
FactoryBoy needs upgrade

### ISSUE THREAD

**Issue by ghost** [kitconcept/robotframework-djangolibrary#26]
Currently, running ``py.test mysite`` raises this error:
```
E   ImportError: The ``fake-factory`` package is now called ``Faker``.
E
E   Please update your requirements.
```
This is an issue which has been resolved in FactoryBoy: https://github.com/FactoryBoy/factory_boy/issues/334
Faker changed the way it should be imported and because the version of Faker was loosely specified in FactoryBoy requirements, a build that used to work doesn't work anymore.
I can send a PR with an updated ``requirements.txt`` if that helps.

**Comment by tisto** [comment]
@amarandon thanks for the bug report! A pull request with an updated requirements would be highly appreciated. I'd be happy to review, merge and release...
