### ISSUE TITLE
Port to Django 1.10

### ISSUE THREAD

**Issue by ghost** [kitconcept/robotframework-djangolibrary#30]
With Django 1.10 middleware tests raise this exception:

`E       TypeError: <QuerySet []> is not JSON serializable`

I'm not sure yet how to fix it.

**Comment by tisto** [comment]
https://github.com/kitconcept/robotframework-djangolibrary/pull/32

**Comment by tisto** [comment]
I just found the reason for this problem:

"Private API django.forms.models.model_to_dict() returns a queryset rather than a list of primary keys for ManyToManyFields."

https://django-doc-test-kor.readthedocs.io/en/latest/releases/1.10.html

**Comment by tisto** [comment]
I fixed the issue in #32.

**Comment by tisto** [comment]
Fix merged. Closing the issue.
