### ISSUE TITLE
`pybot` usage in README (and possibly elsewhere) should be changed to `robot`

### ISSUE THREAD

**Issue by pekkaklarck** [kitconcept/robotframework-djangolibrary#65]
`pybot` won't work with RF 3.1 anymore. See robotframework/robotframework#2818 for details.

**Comment by tisto** [comment]
@pekkaklarck thanks for pointing that out. Will look into it!

**Comment by tisto** [comment]
@pekkaklarck fixed in https://github.com/kitconcept/robotframework-djangolibrary/pull/66
